#! /bin/bash

apt update
apt upgrade
apt install \
    vim-gtk \
    tmux \
    git \
    build-essential \
    htop \
    mosh \
    gnome-tweaks \
    ripgrep \

# Configure tmux
echo "set -g default-terminal \"screen-256color\"\nset -g mouse on\nbind c new-window -c \"#{pane_current_path}\" " > ~/.tmux.conf
cat << EOF > ~/.tmux.conf
set -g default-terminal "screen-256color"
set -g mouse on
bind c new-window        -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h   -c "#{pane_current_path}"
EOF
