#! /bin/bash

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
echo 'eval (/home/linuxbrew/.linuxbrew/bin/brew shellenv)' \
  >> ~/.config/fish/config.fish
brew install gcc fzf
# Install fuzzy-completion
~/linuxbrew/.linuxbrew/opt/fzf/install
