#! /bin/bash

brew install gh
gh auth login
git config --global init.defaultBranch main
git config --global user.email alexfaber2011@gmail.com
git config --global user.name Alex Faber

# Add aliases if they're not already there
if [ -z $(grep alias ~/.gitconfig) ]; then
cat << EOF >> ~/.gitconfig
[alias]
  co = checkout
  ci = commit
  s = status
  br = branch
  hist = log --pretty=format:\"%h %ad | %s%d [%an]\" --graph --date=short
  type = cat-file -t
  dump = cat-file -p
  gap = add --patch
EOF
fi
