#! /bin/bash

# Install Node via n
if [[ -z $(which n) ]]; then
  curl -L https://git.io/n-install | bash
  printf "\n\nrun '. ~/.config/fish/config.fish' and then fire script up again"
  exit 0
fi

# Install Global node packages
npm install -g typescript
npm install -g yarn
