#! /bin/bash

mkdir -p ~/.vim
cd ~/.vim
git clone git@github.com:alexfaber2011/vim.git .
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

printf "\nOpen vim and run :PlugInstall"
