#! /bin/bash

sudo echo "deb https://apt.enpass.io/ stable main" > \
  /etc/apt/sources.list.d/enpass.list

 sudo wget -O - https://apt.enpass.io/keys/enpass-linux.key | tee /etc/apt/trusted.gpg.d/enpass.asc

 sudo apt-get update
 sudo apt-get install enpass
