#! /bin/bash

# curl -fsSL https://get.docker.com -o get-docker.sh
# sudo sh get-docker.sh

sudo usermod -aG docker alex
sudo chown root:docker /var/run/docker.sock

printf "\n\nlog out and back in again"
